services:
    web:
        build: .
        environment:
            NODE_ENV: "production"
            BASE_URL: "http://localhost:3000"
            BASE_PORT: 3000
            MONGODB_URL: "mongodb://mongodbuser:EeheeghohhiH7iez7peesho2@mongodb:27017/graphql-sample?authSource=admin"
            # MONGODB_URL: "mongodb://127.0.0.1:27017/graphql-sample?replicaSet=rs0"
        # network_mode: host
        ports:
            - 3000:3000
        depends_on:
            - mongodb
        networks:
            - backend
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongodbuser
            MONGO_INITDB_ROOT_PASSWORD: EeheeghohhiH7iez7peesho2
            MONGO_INITDB_DATABASE: graphql-sample
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend
    mongo-seed:
        build: ./db
        environment:
            USERNAME: mongodbuser
            PASSWORD: EeheeghohhiH7iez7peesho2
            DATABASE: graphql-sample
            HOST: mongodb
        depends_on:
            - mongodb
        networks:
            - backend
networks:
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
